export enum TokenTypeEnum {
  CREATE_USER = 'CREATE_USER',
  CHANGE_PHONE = 'CHANGE_PHONE',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  VERIFY_PHONE = 'VERIFY_PHONE',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  REDEMPTION = 'REDEMPTION',
}
